site_name: DUC Capital Platform Documentation
site_description: Complete guide to Sagacity (Deal Preparation), Bridge (Tokenization), and Lift (Asset Management)
site_author: DUC Team
site_url: https://guide.duc-apps.com

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light-blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light-blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - toc.follow
  language: en
  font:
    text: Inter
    code: Source Code Pro
  icon:
    logo: material/book-open-variant

plugins:
  - search:
      lang: en
  - mermaid2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - footnotes
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/solid/house
      link: https://duc-apps.com
  generator: false

nav:
  - Welcome: index.md
  
  - Platform Overview:
    - Understanding the Capital Platform: getting-started/overview.md
    - Deal Lifecycle Flow: getting-started/lifecycle-flow.md
    - Which Application to Use: getting-started/choosing-app.md
    - Quick Start Guide: getting-started/quick-start.md
  
  - Sagacity - Deal Preparation:
    - What is Sagacity?: sagacity/what-is-sagacity.md
    - Getting Started:
      - First Time Setup: sagacity/getting-started/first-setup.md
      - Dashboard Overview: sagacity/getting-started/dashboard.md
      - Navigation: sagacity/getting-started/navigation.md
    - Deal Lifecycle:
      - Deal Origination: sagacity/deals/origination.md
      - Evaluation & Analysis: sagacity/deals/evaluation.md
      - Structuring: sagacity/deals/structuring.md
      - Due Diligence: sagacity/deals/due-diligence.md
      - Deal Close: sagacity/deals/close.md
    - AI-Driven Tools:
      - Valuation Models: sagacity/ai-tools/valuation.md
      - Risk Analysis: sagacity/ai-tools/risk-analysis.md
      - Market Research: sagacity/ai-tools/market-research.md
      - Financial Modeling: sagacity/ai-tools/financial-modeling.md
    - Deliverables:
      - Investment Committee Memo: sagacity/deliverables/ic-memo.md
      - Valuation Reports: sagacity/deliverables/valuation-reports.md
      - Deal Book Preparation: sagacity/deliverables/deal-book.md
  
  - Bridge - Tokenization Platform:
    - What is Bridge?: bridge/what-is-bridge.md
    - Getting Started:
      - Understanding Tokenization: bridge/getting-started/understanding.md
      - First Token Issuance: bridge/getting-started/first-issuance.md
      - Platform Setup: bridge/getting-started/setup.md
    - Asset Tokenization:
      - Asset Types Overview: bridge/tokenization/asset-types.md
      - Direct Assets: bridge/tokenization/direct-assets.md
      - Fractionalized Assets: bridge/tokenization/fractionalized.md
      - Corporate RWA: bridge/tokenization/corporate-rwa.md
    - Capital Structuring:
      - SPV Setup: bridge/structuring/spv.md
      - Cap Table Management: bridge/structuring/cap-table.md
      - Equity & Debt Instruments: bridge/structuring/instruments.md
    - Compliance & Risk:
      - KYC/AML Processes: bridge/compliance/kyc-aml.md
      - Transfer Restrictions: bridge/compliance/transfer-restrictions.md
      - Covenant Monitoring: bridge/compliance/covenants.md
    - Investor Management:
      - Offer Creation: bridge/investors/offers.md
      - Investor Onboarding: bridge/investors/onboarding.md
      - Registry Management: bridge/investors/registry.md
  
  - Lift - Asset Management:
    - What is Lift?: lift/what-is-lift.md
    - Getting Started:
      - Understanding Lift: lift/getting-started/understanding.md
      - Dashboard Overview: lift/getting-started/dashboard.md
      - Portfolio View: lift/getting-started/portfolio.md
    - Execution Tracking:
      - Project Milestones: lift/execution/milestones.md
      - KPI Monitoring: lift/execution/kpi.md
      - Stage Management: lift/execution/stages.md
    - Asset Performance:
      - Operational Metrics: lift/performance/metrics.md
      - Financial Tracking: lift/performance/financial.md
      - Revenue Performance: lift/performance/revenue.md
    - Compliance & Reporting:
      - Covenant Monitoring: lift/compliance/covenants.md
      - Regulatory Checks: lift/compliance/regulatory.md
      - Performance Reports: lift/compliance/reports.md
    - Portfolio Management:
      - Active Assets View: lift/portfolio/active-assets.md
      - Project Overview: lift/portfolio/projects.md
      - Data Integration: lift/portfolio/data-feeds.md
  
  - Platform Integration:
    - Deal Lifecycle Flow: integration/lifecycle.md
    - Data Flow Architecture: integration/data-flow.md
    - Portfolio Continuity: integration/portfolio.md
    - Performance Feedback Loop: integration/feedback.md
    - Best Practices: integration/best-practices.md
  
  - Resources & Support:
    - Getting Help: help/finding-help.md
    - Glossary: help/glossary.md
    - Training Materials: help/training.md
    - Contact Support: help/contact.md
    - FAQ: help/faq.md