name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mkdocs-with-pdf beautifulsoup4 libsass

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Test documentation build
        run: mkdocs build --strict

      - name: Build HTML documentation
        run: mkdocs build

      - name: Generate PDF documentation
        run: python generate_pdfs.py

      - name: Copy PDFs to site directory
        run: |
          mkdir -p site/pdfs
          cp -r pdfs/* site/pdfs/ 2>/dev/null || true

      - name: Create .nojekyll file
        run: touch site/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4