name: Generate PDF Documentation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Monday at 2 AM UTC
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'generate_pdfs.py'

jobs:
  generate-pdf:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            python3-cffi \
            python3-brotli \
            libpango-1.0-0 \
            libharfbuzz0b \
            libpangocairo-1.0-0 \
            libcairo2 \
            libgdk-pixbuf2.0-0 \
            libffi-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mkdocs-with-pdf beautifulsoup4 libsass

      - name: Generate PDFs
        run: |
          python generate_pdfs.py
          ls -la pdfs/

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation-pdfs
          path: pdfs/
          retention-days: 30

      - name: Create Release (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: pdfs/*.pdf
          body: |
            📚 DUC Capital Platform Documentation PDFs
            
            This release includes PDF versions of:
            - Complete Platform Guide
            - Sagacity Guide (Deal Preparation)
            - Bridge Guide (Tokenization)
            - Lift Guide (Asset Management)
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}